export const HOST = import.meta.env.DEV ? "http://localhost:3001/admin" : 'https://server-muze.onrender.com/admin';
export const getReq = `${HOST}/get-req`;
export const getQueue = `${HOST}/get-queue`;
export const addToQueue = `${HOST}/add-to-queue`;
export const removeFromReqList = `${HOST}/remove-req-list`;
export const removeFromQueue = `${HOST}/remove-from-queue`;
export const addToHistory = `${HOST}/add-to-history`;
export const getSpecificHistory = `${HOST}/get-specific-history`
export const setQueue = `${HOST}/set-queue`;
export const setReqList = `${HOST}/set-req-list`;
export const getPlaylists = `${HOST}/get-playlists`;
export const playlistToQueue = `${HOST}/playlist-to-queue`;
export const createPlaylist = `${HOST}/create-playlist`;